#!/usr/bin/env bash
#
# Tests `trust_state()` from bootstrap-names.sh. No network, npm or auth.
#
# That function decides whether a package is correctly configured for OIDC
# publishing. Getting it wrong is invisible until release day: an entry granting
# nothing still 404s the publish, and — worse — mistaking a failed CHECK for a
# missing entry makes the script tell an operator to revoke a good entry.
#
# Run: bash npm/test-bootstrap-names.sh

set -uo pipefail

SCRIPT_UNDER_TEST="$(dirname "$0")/bootstrap-names.sh"
# shellcheck disable=SC2034  # read by the function eval'd in below
REPO="bugsee/bugsee-cli"
# shellcheck disable=SC2034
WORKFLOW="npm-publish.yml"

FIXTURE=""
FIXTURE_STATUS=0

# Stands in for `$TRUST_NPM trust list <pkg> [--json]`. Returns the fixture for
# the shape being tested and ignores the other, so a test can exercise the JSON
# path or the text fallback independently.
# "text"  -> an npm with no --json support (the --json call fails)
# "json"  -> --json answers, text is never reached
# "both"  -> --json answers with $FIXTURE, exactly like a modern npm
FIXTURE_MODE="text"
# fake_npm is reached only through $TRUST_NPM, which shellcheck cannot see.
# SC2329 and SC2317 are the same finding in different shellcheck generations.
# shellcheck disable=SC2329,SC2317
fake_npm() {
  local json=0
  for a in "$@"; do [ "$a" = "--json" ] && json=1; done
  case "$FIXTURE_MODE" in
    both) printf '%s' "$FIXTURE"; return "$FIXTURE_STATUS" ;;
    json) [ "$json" = 1 ] && { printf '%s' "$FIXTURE"; return "$FIXTURE_STATUS"; }; return 1 ;;
    text) [ "$json" = 0 ] && { printf '%s' "$FIXTURE"; return "$FIXTURE_STATUS"; }; return 1 ;;
  esac
  return 1
}
# shellcheck disable=SC2034
TRUST_NPM="fake_npm"

# shellcheck disable=SC1090
eval "$(awk '/^trust_state\(\) \{/,/^\}/' "$SCRIPT_UNDER_TEST")"

fails=0
t() {
  local name="$1" expected="$2" mode="$3" status="$4"
  FIXTURE_MODE="$mode"; FIXTURE="$5"; FIXTURE_STATUS="$status"
  local got; got="$(trust_state "@bugsee/x")"
  if [ "$got" = "$expected" ]; then
    printf '  ok    %s\n' "$name"
  else
    printf '  FAIL  %s (expected %s, got %s)\n' "$name" "$expected" "$got"
    fails=1
  fi
}

# ---- the state that must never be guessed --------------------------------
# npm errored. Previously this returned "not configured", and the script then
# advised revoking a possibly-correct entry.
t "npm failing is 'unknown', not 'absent'" unknown text 1 ''
t "npm failing WHILE printing a good entry is still 'unknown'" unknown text 1 '
type: github
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish
'
t "unparseable JSON is 'unknown'" unknown json 0 'not json at all'

# ---- an entry that exists but grants nothing ------------------------------
# What npm < 11.15 creates. Distinct from 'absent' because npm allows only one
# configuration per package: it must be REVOKED, not re-added.
t "stage-publish only is 'other'" other text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: stage publish
'
t "an entry with no permissions line is 'other'" other text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
'

# ---- granted -------------------------------------------------------------
t "publish among several permissions is 'granted'" granted text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish, stage publish
'
t "publish alone is 'granted'" granted text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish
'
# CRLF and trailing spaces: the old parser trimmed only the prefix, so a CR made
# a correct entry read as absent -> the script re-added it and errored.
# The CRs are generated by printf at RUNTIME. Literal CR bytes in this file
# would be normalised to LF by git (core.autocrlf / .gitattributes), silently
# turning this into a plain-LF case that proves nothing.
t "CRLF output still matches" granted text 0 "$(printf 'type: github\r\nfile: npm-publish.yml\r\nrepository: bugsee/bugsee-cli\r\npermissions: publish\r\n')"
t "trailing whitespace still matches" granted text 0 '
type: github
file: npm-publish.yml   
repository: bugsee/bugsee-cli  
permissions: publish  
'

# ---- absent --------------------------------------------------------------
t "no entries at all is 'absent'" absent text 0 ''
t "an entry for another workflow is 'absent'" absent text 0 '
type: github
file: release.yml
repository: bugsee/bugsee-cli
permissions: publish
'
t "an entry for another repository is 'absent'" absent text 0 '
type: github
file: npm-publish.yml
repository: someone/else
permissions: publish
'

# ---- the JSON path -------------------------------------------------------
t "JSON: publish granted" granted json 0 '[{"type":"github","id":"a","file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["publish","stage publish"]}]'
t "JSON: stage-publish only is 'other'" other json 0 '[{"type":"github","id":"a","file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["stage publish"]}]'
t "JSON: empty list is 'absent'" absent json 0 '[]'
t "JSON: another workflow is 'absent'" absent json 0 '[{"file":"release.yml","repository":"bugsee/bugsee-cli","permissions":["publish"]}]'
t "JSON: nested under a key still found" granted json 0 '{"trustedPublishers":[{"file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["publish"]}]}'
# A shape we do not recognise must not be reported as a confident 'absent'.
t "JSON: unrecognised shape is 'unknown'" unknown json 0 '{"somethingElse":{"a":1}}'

# ---- entries that are NOT blank-line separated ---------------------------
# A paragraph parser merges these and the LAST file:/repository:/permissions:
# win, reporting `granted` for a package whose own entry grants nothing — the
# one wrong answer this function exists to prevent.
t "merged entries do not leak permissions across" other text 0 'file: release.yml
repository: bugsee/bugsee-cli
permissions: publish
type: github
file: npm-publish.yml
repository: bugsee/bugsee-cli'

t "ours second and granted, no blank line" granted text 0 'type: github
file: release.yml
repository: bugsee/bugsee-cli
permissions: stage publish
type: github
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish'

# ---- output we do not understand ----------------------------------------
# Distinct from "no entries": the text path is used by exactly the npm versions
# whose format is least known, so it must not guess.
t "prose instead of fields is 'unknown'" unknown text 0 'No trusted publishers configured.'
t "different field labels are 'unknown'" unknown text 0 'workflow: npm-publish.yml
repo: bugsee/bugsee-cli
grants: publish'

# ...but genuinely empty output IS "no entries", which is the normal state of a
# freshly published placeholder. Getting this wrong would make bootstrapping a
# new name impossible.
t "empty text output is 'absent'" absent text 0 ''

# ---- rendering differences ----------------------------------------------
t "a path-qualified workflow still matches" granted text 0 'type: github
file: .github/workflows/npm-publish.yml
repository: https://github.com/bugsee/bugsee-cli.git
permissions: publish'

# ---- the JSON path, harder cases ----------------------------------------
t "JSON: a bare null is 'unknown', not 'absent'" unknown both 0 'null'
t "JSON: unrelated metadata does not disarm the guard" unknown both 0 '{"meta":{"file":"x","repository":"y"},"weird":{"a":1}}'
t "JSON: npm supporting --json with no entries is 'absent'" absent both 0 '[]'
t "JSON: a non-zero --json call falls back, not 'absent'" unknown json 1 '[]'

if [ "$fails" -eq 0 ]; then
  echo "all trust_state cases pass"
else
  echo "trust_state FAILURES" >&2
fi
exit "$fails"
