#!/usr/bin/env bash
#
# Tests `trust_state()` from bootstrap-names.sh. No network, npm or auth.
#
# That function decides whether a package is correctly configured for OIDC
# publishing. Getting it wrong is invisible until release day: an entry granting
# nothing still 404s the publish, and — worse — mistaking a failed CHECK for a
# missing entry makes the script tell an operator to revoke a good entry.
#
# Run: bash npm/test-bootstrap-names.sh

set -uo pipefail

SCRIPT_UNDER_TEST="$(dirname "$0")/bootstrap-names.sh"
# shellcheck disable=SC2034  # read by the function eval'd in below
REPO="bugsee/bugsee-cli"
# shellcheck disable=SC2034
WORKFLOW="npm-publish.yml"

FIXTURE=""
FIXTURE_STATUS=0

# Stands in for `$TRUST_NPM trust list <pkg> [--json]`. Returns the fixture for
# the shape being tested and ignores the other, so a test can exercise the JSON
# path or the text fallback independently.
# "text"  -> an npm with no --json support (the --json call fails)
# "json"  -> --json answers, text is never reached
# "both"  -> --json answers with $FIXTURE, exactly like a modern npm
FIXTURE_MODE="text"
# fake_npm is reached only through $TRUST_NPM, which shellcheck cannot see.
# SC2329 and SC2317 are the same finding in different shellcheck generations.
# shellcheck disable=SC2329,SC2317
fake_npm() {
  local json=0
  for a in "$@"; do [ "$a" = "--json" ] && json=1; done
  case "$FIXTURE_MODE" in
    both) printf '%s' "$FIXTURE"; return "$FIXTURE_STATUS" ;;
    json) [ "$json" = 1 ] && { printf '%s' "$FIXTURE"; return "$FIXTURE_STATUS"; }; return 1 ;;
    text) [ "$json" = 0 ] && { printf '%s' "$FIXTURE"; return "$FIXTURE_STATUS"; }; return 1 ;;
  esac
  return 1
}
# shellcheck disable=SC2034
TRUST_NPM="fake_npm"

# shellcheck disable=SC1090
eval "$(awk '/^trust_state\(\) \{/,/^\}/' "$SCRIPT_UNDER_TEST")"
# shellcheck disable=SC1090
eval "$(awk '/^trust_state_interactive\(\) \{/,/^\}/' "$SCRIPT_UNDER_TEST")"

fails=0
t() {
  local name="$1" expected="$2" mode="$3" status="$4"
  FIXTURE_MODE="$mode"; FIXTURE="$5"; FIXTURE_STATUS="$status"
  local got; got="$(trust_state "@bugsee/x")"
  if [ "$got" = "$expected" ]; then
    printf '  ok    %s\n' "$name"
  else
    printf '  FAIL  %s (expected %s, got %s)\n' "$name" "$expected" "$got"
    fails=1
  fi
}

# ---- CAPTURED FROM A REAL REGISTRY -----------------------------------------
# Verbatim `npx npm@latest trust list @bugsee/cli-win32-arm64` output, npm
# 12.x, 2026-09-16. Every other fixture here was written to match the parser,
# which proves the parser self-consistent and nothing about npm; this one is
# the other way round. Do not "tidy" it — the leading blank line and the exact
# labels are the point.
t "real npm output is classified granted" granted text 0 '
type: github
id: 6827c0f2-26cd-49fc-9cd3-374f7bb1d3b2
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish, stage publish
'

# ---- the state that must never be guessed --------------------------------
# npm errored. Previously this returned "not configured", and the script then
# advised revoking a possibly-correct entry.
t "npm failing is 'unknown', not 'absent'" unknown text 1 ''
t "npm failing WHILE printing a good entry is still 'unknown'" unknown text 1 '
type: github
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish
'
t "unparseable JSON is 'unknown'" unknown json 0 'not json at all'

# ---- an entry that exists but grants nothing ------------------------------
# What npm < 11.15 creates. Distinct from 'absent' because npm allows only one
# configuration per package: it must be REVOKED, not re-added.
t "stage-publish only is 'other'" other text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: stage publish
'
t "an entry with no permissions line is 'other'" other text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
'

# ---- granted -------------------------------------------------------------
t "publish among several permissions is 'granted'" granted text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish, stage publish
'
t "publish alone is 'granted'" granted text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish
'
# CRLF and trailing spaces: the old parser trimmed only the prefix, so a CR made
# a correct entry read as absent -> the script re-added it and errored.
# The CRs are generated by printf at RUNTIME. Literal CR bytes in this file
# would be normalised to LF by git (core.autocrlf / .gitattributes), silently
# turning this into a plain-LF case that proves nothing.
t "CRLF output still matches" granted text 0 "$(printf 'type: github\r\nfile: npm-publish.yml\r\nrepository: bugsee/bugsee-cli\r\npermissions: publish\r\n')"
t "trailing whitespace still matches" granted text 0 '
type: github
file: npm-publish.yml   
repository: bugsee/bugsee-cli  
permissions: publish  
'

# ---- absent --------------------------------------------------------------
t "no entries at all is 'absent'" absent text 0 ''
t "an entry for another workflow is 'absent'" absent text 0 '
type: github
file: release.yml
repository: bugsee/bugsee-cli
permissions: publish
'
t "an entry for another repository is 'absent'" absent text 0 '
type: github
file: npm-publish.yml
repository: someone/else
permissions: publish
'

# ---- the JSON path -------------------------------------------------------
t "JSON: publish granted" granted json 0 '[{"type":"github","id":"a","file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["publish","stage publish"]}]'
t "JSON: stage-publish only is 'other'" other json 0 '[{"type":"github","id":"a","file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["stage publish"]}]'
t "JSON: empty list is 'absent'" absent json 0 '[]'
t "JSON: another workflow is 'absent'" absent json 0 '[{"file":"release.yml","repository":"bugsee/bugsee-cli","permissions":["publish"]}]'
t "JSON: nested under a key still found" granted json 0 '{"trustedPublishers":[{"file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["publish"]}]}'
# A shape we do not recognise must not be reported as a confident 'absent'.
t "JSON: unrecognised shape is 'unknown'" unknown json 0 '{"somethingElse":{"a":1}}'

# ---- entries that are NOT blank-line separated ---------------------------
# A paragraph parser merges these and the LAST file:/repository:/permissions:
# win, reporting `granted` for a package whose own entry grants nothing — the
# one wrong answer this function exists to prevent.
t "merged entries do not leak permissions across" other text 0 'file: release.yml
repository: bugsee/bugsee-cli
permissions: publish
type: github
file: npm-publish.yml
repository: bugsee/bugsee-cli'

t "ours second and granted, no blank line" granted text 0 'type: github
file: release.yml
repository: bugsee/bugsee-cli
permissions: stage publish
type: github
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish'

# ---- output we do not understand ----------------------------------------
# Distinct from "no entries": the text path is used by exactly the npm versions
# whose format is least known, so it must not guess.
t "prose instead of fields is 'unknown'" unknown text 0 'No trusted publishers configured.'
t "different field labels are 'unknown'" unknown text 0 'workflow: npm-publish.yml
repo: bugsee/bugsee-cli
grants: publish'

# ...but genuinely empty output IS "no entries", which is the normal state of a
# freshly published placeholder. Getting this wrong would make bootstrapping a
# new name impossible.
t "empty text output is 'absent'" absent text 0 ''

# ---- rendering differences ----------------------------------------------
t "a path-qualified workflow still matches" granted text 0 'type: github
file: .github/workflows/npm-publish.yml
repository: https://github.com/bugsee/bugsee-cli.git
permissions: publish'

# ---- the JSON path, harder cases ----------------------------------------
t "JSON: a bare null is 'unknown', not 'absent'" unknown both 0 'null'
t "JSON: unrelated metadata does not disarm the guard" unknown both 0 '{"meta":{"file":"x","repository":"y"},"weird":{"a":1}}'
t "JSON: npm supporting --json with no entries is 'absent'" absent both 0 '[]'
t "JSON: a non-zero --json call falls back, not 'absent'" unknown json 1 '[]'

# ---- the uncaptured retry ---------------------------------------------------
# This is the half the 28 fixtures above CANNOT see: they stub npm out, so the
# interaction between command substitution and npm's 2FA prompt is invisible to
# them. The retry lived inline in the caller, and a mutation deleting it passed
# every one of them.
#
# A fake npm that fails its first two (CAPTURED) reads and answers afterwards
# stands in for the real failure mode: captured stdout -> EOTP -> `unknown`, then
# an uncaptured call that authenticates, then a re-read that succeeds. It also has
# no `--json` support, like the npm that produced the text fixture above.
REAL_ENTRY='
type: github
id: 6827c0f2-26cd-49fc-9cd3-374f7bb1d3b2
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish, stage publish
'
# The call count lives in a FILE, not a variable: `trust_state` is invoked through
# `$(...)`, and a subshell's increments die with it — which is why a first attempt
# at this test saw the retry happen and still read `unknown`.
# shellcheck disable=SC2329,SC2317
flaky_npm() {
  local json=0 n
  for a in "$@"; do [ "$a" = "--json" ] && json=1; done
  n=$(( $(cat "$CALL_FILE") + 1 ))
  echo "$n" > "$CALL_FILE"
  [ "$json" = 1 ] && return 1
  [ "$n" -le "$FAIL_FIRST" ] && return 1
  printf '%s' "$REAL_ENTRY"
}

# Asserts the classification AND whether the interactive retry was used, because
# "granted either way" cannot tell a working retry from one that always runs.
#
# The state is read from TRUST_STATE and compared EXACTLY — no `tail -1`. An
# earlier version of this test took the function's stdout and stripped the last
# line off it, which quietly accommodated the bug the reviewer found: the state
# was arriving with npm's output glued to it, and a real caller has no `tail`.
# Stdout goes to a FILE here for the same reason the real call site leaves it
# attached to the terminal — capturing it with `$(...)` would put the function in
# a subshell and lose TRUST_STATE with it.
ti() {
  local name="$1" expected="$2" want_retry="$3" out retried
  CALL_FILE="$(mktemp)"; echo 0 > "$CALL_FILE"
  local out_file; out_file="$(mktemp)"
  TRUST_STATE=""
  TRUST_NPM=flaky_npm trust_state_interactive "@bugsee/x" > "$out_file" 2>/dev/null
  out="$(cat "$out_file")"
  case "$out" in *"needs an interactive 2FA challenge"*) retried=yes ;; *) retried=no ;; esac
  rm -f "$CALL_FILE" "$out_file"
  if [ "$TRUST_STATE" = "$expected" ] && [ "$retried" = "$want_retry" ]; then
    printf '  ok    %s\n' "$name"
  else
    printf '  FAIL  %s (expected %s/retry=%s, got %s/retry=%s)\n' \
      "$name" "$expected" "$want_retry" "$TRUST_STATE" "$retried"
    fails=1
  fi
}

# The call site itself, which no amount of driving the function can check: wrapping
# it in a command substitution recaptures the stdout npm's prompt needs, and the
# multi-line value then matches no arm of the caller's `case`. That is precisely
# the regression the reviewer caught, so it is pinned structurally.
# Comments stripped first: this file's own explanation of the hazard, and the
# script's, both contain the very shape being searched for.
if grep -vE '^[[:space:]]*#' "$SCRIPT_UNDER_TEST" | grep -qE '[$][(][[:space:]]*trust_state_interactive'; then
  printf '  FAIL  trust_state_interactive is called in a command substitution — recaptures the 2FA prompt\n'
  fails=1
else
  printf '  ok    the interactive read is not wrapped in a command substitution\n'
fi

# A cold session: the captured reads fail, so the retry is what rescues it.
FAIL_FIRST=2
ti "an EOTP-failing captured read is retried uncaptured, then classified" granted yes

# A warm session answers immediately, and nothing is retried — so a session
# already authenticated is never prompted.
FAIL_FIRST=0
ti "a session that already answers is classified without a retry" granted no

if [ "$fails" -eq 0 ]; then
  echo "all trust_state cases pass"
else
  echo "trust_state FAILURES" >&2
fi
exit "$fails"
