#!/usr/bin/env bash
#
# Tests `trust_state()` from bootstrap-names.sh. No network, npm or auth.
#
# That function decides whether a package is correctly configured for OIDC
# publishing. Getting it wrong is invisible until release day: an entry granting
# nothing still 404s the publish, and — worse — mistaking a failed CHECK for a
# missing entry makes the script tell an operator to revoke a good entry.
#
# Run: bash npm/test-bootstrap-names.sh

set -uo pipefail

SCRIPT_UNDER_TEST="$(dirname "$0")/bootstrap-names.sh"
# shellcheck disable=SC2034  # read by the function eval'd in below
REPO="bugsee/bugsee-cli"
# shellcheck disable=SC2034
WORKFLOW="npm-publish.yml"

FIXTURE=""
FIXTURE_STATUS=0

# Stands in for `$TRUST_NPM trust list <pkg> [--json]`. Returns the fixture for
# the shape being tested and ignores the other, so a test can exercise the JSON
# path or the text fallback independently.
FIXTURE_MODE="text"
# shellcheck disable=SC2329
fake_npm() {
  local json=0
  for a in "$@"; do [ "$a" = "--json" ] && json=1; done
  if { [ "$json" = 1 ] && [ "$FIXTURE_MODE" = "json" ]; } ||
     { [ "$json" = 0 ] && [ "$FIXTURE_MODE" = "text" ]; }; then
    printf '%s' "$FIXTURE"
    return "$FIXTURE_STATUS"
  fi
  # Wrong shape for this fixture: behave like an npm that does not support it.
  return 1
}
# shellcheck disable=SC2034
TRUST_NPM="fake_npm"

# shellcheck disable=SC1090
eval "$(awk '/^trust_state\(\) \{/,/^\}/' "$SCRIPT_UNDER_TEST")"

fails=0
t() {
  local name="$1" expected="$2" mode="$3" status="$4"
  FIXTURE_MODE="$mode"; FIXTURE="$5"; FIXTURE_STATUS="$status"
  local got; got="$(trust_state "@bugsee/x")"
  if [ "$got" = "$expected" ]; then
    printf '  ok    %s\n' "$name"
  else
    printf '  FAIL  %s (expected %s, got %s)\n' "$name" "$expected" "$got"
    fails=1
  fi
}

# ---- the state that must never be guessed --------------------------------
# npm errored. Previously this returned "not configured", and the script then
# advised revoking a possibly-correct entry.
t "npm failing is 'unknown', not 'absent'" unknown text 1 ''
t "npm failing WHILE printing a good entry is still 'unknown'" unknown text 1 '
type: github
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish
'
t "unparseable JSON is 'unknown'" unknown json 0 'not json at all'

# ---- an entry that exists but grants nothing ------------------------------
# What npm < 11.15 creates. Distinct from 'absent' because npm allows only one
# configuration per package: it must be REVOKED, not re-added.
t "stage-publish only is 'other'" other text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: stage publish
'
t "an entry with no permissions line is 'other'" other text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
'

# ---- granted -------------------------------------------------------------
t "publish among several permissions is 'granted'" granted text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish, stage publish
'
t "publish alone is 'granted'" granted text 0 '
type: github
id: abc
file: npm-publish.yml
repository: bugsee/bugsee-cli
permissions: publish
'
# CRLF and trailing spaces: the old parser trimmed only the prefix, so a CR made
# a correct entry read as absent -> the script re-added it and errored.
# The CRs are generated by printf at RUNTIME. Literal CR bytes in this file
# would be normalised to LF by git (core.autocrlf / .gitattributes), silently
# turning this into a plain-LF case that proves nothing.
t "CRLF output still matches" granted text 0 "$(printf 'type: github\r\nfile: npm-publish.yml\r\nrepository: bugsee/bugsee-cli\r\npermissions: publish\r\n')"
t "trailing whitespace still matches" granted text 0 '
type: github
file: npm-publish.yml   
repository: bugsee/bugsee-cli  
permissions: publish  
'

# ---- absent --------------------------------------------------------------
t "no entries at all is 'absent'" absent text 0 ''
t "an entry for another workflow is 'absent'" absent text 0 '
type: github
file: release.yml
repository: bugsee/bugsee-cli
permissions: publish
'
t "an entry for another repository is 'absent'" absent text 0 '
type: github
file: npm-publish.yml
repository: someone/else
permissions: publish
'

# ---- the JSON path -------------------------------------------------------
t "JSON: publish granted" granted json 0 '[{"type":"github","id":"a","file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["publish","stage publish"]}]'
t "JSON: stage-publish only is 'other'" other json 0 '[{"type":"github","id":"a","file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["stage publish"]}]'
t "JSON: empty list is 'absent'" absent json 0 '[]'
t "JSON: another workflow is 'absent'" absent json 0 '[{"file":"release.yml","repository":"bugsee/bugsee-cli","permissions":["publish"]}]'
t "JSON: nested under a key still found" granted json 0 '{"trustedPublishers":[{"file":"npm-publish.yml","repository":"bugsee/bugsee-cli","permissions":["publish"]}]}'
# A shape we do not recognise must not be reported as a confident 'absent'.
t "JSON: unrecognised shape is 'unknown'" unknown json 0 '{"somethingElse":{"a":1}}'

if [ "$fails" -eq 0 ]; then
  echo "all trust_state cases pass"
else
  echo "trust_state FAILURES" >&2
fi
exit "$fails"
